#!/usr/bin/env python3
"""Generate port/sources.cmake from the decomp's configure.py object list.

Only the game, JSystem, nw4r and RVLFaceLib objects are part of the host
build; the RVL SDK, MSL, Metrowerks runtime and MetroTRK are replaced by the
port layer.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
KEEP = ("GameLib", "NWLib", "JSysLib", "JSys_J3DLib", "JSys_JAudioLib", "JSys_JParticleLib", "RFLib")

text = open(os.path.join(ROOT, "configure.py")).read()
# Split into top-level library calls: `    Name(` at 4-space indent.
parts = re.split(r"\n    (?=[A-Za-z_]+\(|\{)", text)
groups = {}
for part in parts:
    m = re.match(r"([A-Za-z_]+)\(", part)
    kind = m.group(1) if m else "dict"
    if kind not in KEEP:
        continue
    for path in re.findall(r'Object\(\s*\w+\s*,\s*"([^"]+)"', part):
        top = path.split("/")[0]
        groups.setdefault(top, []).append(path)

out = ["# Generated by port/tools/gen_sources.py from configure.py; do not edit.", ""]
for top in sorted(groups):
    var = "SMG_SOURCES_" + re.sub(r"\W", "_", top).upper()
    out.append(f"set({var}")
    for p in sorted(set(groups[top])):
        if os.path.exists(os.path.join(ROOT, "src", p)):
            out.append(f"    src/{p}")
    out.append(")")
    out.append("")
open(os.path.join(ROOT, "port", "sources.cmake"), "w").write("\n".join(out))
for top in sorted(groups):
    print(top, len(set(groups[top])))
